name: 'PyPi-data toolchain: Update readme'
description: 'PyPi-data toolchain: Update readme'
inputs:
  workspace:
    description: 'Path to github workspace'
    required: true
outputs: {}
runs:
  using: "composite"
  steps:
    - uses: robinraju/release-downloader@v1.8
      with:
        repository: "pypi-data/toolchain"
        fileName: "pypi-data-toolchain.tar.gz"
        extract: true
        latest: true
        out-file-path: "toolchain"
    - shell: bash
      run: |
        ${{ inputs.workspace }}/toolchain/pypi-data-toolchain --version

    - shell: bash
      run: |
        ${{ inputs.workspace }}/toolchain/pypi-data-toolchain generate-readme ${{ inputs.workspace }} > README.md

    - shell: bash
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add README.md
        git commit -m "Update README.md"

    - name: push code
      shell: bash
      run: |
        git config http.postBuffer 524288000
        git -C ${{ inputs.workspace }} push origin +main:main
