name: 'PyPi-data toolchain'
description: 'PyPi-data toolchain'
inputs:
  push:  # id of input
    description: 'Push ref?'
    required: false
    default: 'true'
  token: # id of input
    description: 'Github token'
    required: true
outputs: {}
runs:
  using: "composite"
  steps:
    - uses: robinraju/release-downloader@v1.8
      with:
        repository: "pypi-data/toolchain"
        fileName: "pypi-data-toolchain.tar.gz"
        extract: true
        latest: true
        out-file-path: "toolchain"
    - shell: bash
      run: |
        $GITHUB_WORKSPACE/toolchain/pypi-data-toolchain --version

    - shell: bash
      run: |
        $GITHUB_WORKSPACE/toolchain/pypi-data-toolchain ci $GITHUB_WORKSPACE --limit=10

    - shell: bash
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add index.json
        git commit -m "Add changes"

    - name: push code
      shell: bash
      run: |
        git push code:code

#    - name: Push changes
#      uses: ad-m/github-push-action@master
#      if: ${{ inputs.push == 'true' }}
#      with:
#        github_token: ${{ inputs.token }}
#        branch: ${{ github.ref }}

#    - name: Push changes
#      uses: ad-m/github-push-action@master
#      with:
#        branch: code/

#        mkdir $GITHUB_WORKSPACE/git-test/
#        git config --global init.defaultBranch main
#        git init $GITHUB_WORKSPACE/git-test/
#        cp example/index.json $GITHUB_WORKSPACE/git-test/index.json

#        ls $GITHUB_WORKSPACE/git-test/
        


#        ./$GITHUB_WORKSPACE/toolchain/pypi-data-toolchain --version
