[package]
name = "pypi-data-toolchain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.71", features = ["backtrace"] }
base64 = "0.21.2"
bzip2 = "0.4.4"
chrono = { version = "0.4.26", features = ["serde"] }
clap = { version = "4.3.8", features = ["derive", "env"] }
cli-table = { version = "0.4.7", default-features = false }
content_inspector = "0.2.4"
data-encoding = "2.4.0"
flate2 = { version = "1.0.26", features = ["zlib-ng-compat"], default-features = false }
git2 = { version = "0.17.2", features = ["vendored-libgit2", "vendored-openssl"] }
graphql_client = "0.13.0"
humansize = "2.1.3"
indicatif = { version = "0.17.5", features = ["rayon"] }
itertools = "0.11.0"
lazy-regex = { version = "2.5.0", features = ["perf", "perf-inline", "perf-cache", "perf-dfa", "perf-literal", "unicode"] }
osshkeys = "0.7.0"
parquet = "43.0.0"
parquet_derive = "43.0.0"
polars = { version = "0.30.0", default-features = false, features = ["polars-lazy", "lazy", "parquet", "algo", "rank"] }
rand = "0.8.5"
rayon = "1.7.0"
ring = "0.16.20"
rusqlite = { version = "0.29.0", features = ["bundled", "chrono", "serde_json", "url"] }
serde = { version = "1.0.164", features = ["derive"] }
serde_json = { version = "1.0.99", features = ["preserve_order"] }
sodiumoxide = "0.2.7"
tar = "0.4.38"
tempdir = "0.3.7"
thiserror = "1.0.43"
tinytemplate = "1.2.1"
ureq = { version = "2.7.1", features = ["tls", "json"] }
url = { version = "2.4.0", features = ["serde"] }
zip = { version = "0.6.6", features = ["deflate-zlib", "deflate", "zstd"] }
#
#[profile.release]
#lto = true
