[package]
name = "pypi-data-toolchain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.71", features = ["backtrace"] }
arrow = { version = "43.0.0", features = ["chrono-tz"] }
base64 = "0.21.2"
bzip2 = "0.4.4"
chrono = { version = "0.4.26", features = ["serde"] }
clap = { version = "4.3.8", features = ["derive", "env"] }
content_inspector = "0.2.4"
data-encoding = "2.4.0"
flate2 = { version = "1.0.26", features = ["zlib-ng-compat"], default-features = false }
git2 = { version = "0.17.2", features = ["vendored-libgit2", "vendored-openssl"] }
graphql_client = "0.13.0"
indicatif = { version = "0.17.5", features = ["rayon"] }
itertools = "0.11.0"
lazy-regex = { version = "2.5.0", features = ["perf", "perf-inline", "perf-cache", "perf-dfa", "perf-literal", "unicode"] }
parquet = "42.0.0"
parquet_derive = "42.0.0"
prettytable-rs = "0.10.0"
rayon = "1.7.0"
ring = "0.16.20"
rusqlite = { version = "0.29.0", features = ["bundled", "chrono", "serde_json", "url"] }
serde = { version = "1.0.164", features = ["derive"] }
serde_json = { version = "1.0.99", features = ["preserve_order"] }
tar = "0.4.38"
thiserror = "1.0.40"
tinytemplate = "1.2.1"
ureq = { version = "2.7.1", features = ["tls", "json"] }
url = { version = "2.4.0", features = ["serde"] }
zip = { version = "0.6.6", features = ["deflate-zlib", "deflate", "zstd"] }

[profile.release]
lto = true
