name: 'PyPi-data toolchain'
description: 'PyPi-data toolchain'
inputs:
  push:
    description: 'Push ref?'
    required: false
    default: 'true'
  token:
    description: 'Github token'
    required: true
  workspace:
    description: 'Path to github workspace'
    required: true
  run-id:
    description: 'Github actions run ID'
    required: true
outputs: {}
runs:
  using: "composite"
  steps:
    - uses: robinraju/release-downloader@v1.8
      with:
        repository: "pypi-data/toolchain"
        fileName: "pypi-data-toolchain.tar.gz"
        extract: true
        latest: true
        out-file-path: "toolchain"
    - shell: bash
      run: |
        ${{ inputs.workspace }}/toolchain/pypi-data-toolchain --version

    - shell: bash
      run: |
        ${{ inputs.workspace }}/toolchain/pypi-data-toolchain ci ${{ inputs.workspace }} ${{ inputs.workspace }} --pack-size=200M --limit=10 --index-file-name=index-${{ inputs.run-id }}.parquet

    - shell: bash
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add index.json
        git commit -m "Add changes"
        
        git log -n 1 code
#
#    - name: Archive production artifacts
#      uses: actions/upload-artifact@v3
#      with:
#        name: dist-without-markdown
#        path: |
#          .git/objects/pack/

    - name: push code
      shell: bash
      run: |
        git config http.postBuffer 524288000
        du -hs .git/objects/pack/*
        git -C ${{ inputs.workspace }} push --atomic origin refs/heads/code:refs/heads/code +main:main

    - name: Publish
      uses: softprops/action-gh-release@v1
      with:
        draft: false
        name: "Index"
        tag_name: "latest"
#        draft: false
#        name: "Index ${{ inputs.run-id }}"
#        tag_name: "run-${{ inputs.run-id }}"
#        target_commitish: "refs/heads/code"
        files: 'index-${{ inputs.run-id }}.parquet'
        token: ${{ inputs.token }}


#        git push origin code

#    - name: Push changes
#      uses: ad-m/github-push-action@master
#      if: ${{ inputs.push == 'true' }}
#      with:
#        github_token: ${{ inputs.token }}
#        branch: ${{ github.ref }}

#    - name: Push changes
#      uses: ad-m/github-push-action@master
#      with:
#        branch: code/

#        mkdir $GITHUB_WORKSPACE/git-test/
#        git config --global init.defaultBranch main
#        git init $GITHUB_WORKSPACE/git-test/
#        cp example/index.json $GITHUB_WORKSPACE/git-test/index.json

#        ls $GITHUB_WORKSPACE/git-test/
        


#        ./$GITHUB_WORKSPACE/toolchain/pypi-data-toolchain --version
