on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

name: Build
concurrency: build

jobs:
  build_and_test:
    name: Compile toolchain
    runs-on: ubuntu-latest
    if: github.repository == 'pypi-data/internal-toolchain'
    env:
      RUST_BACKTRACE: "1"
      BUILD_PROFILE_NAME: ${{ (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && 'optimized' || 'release' }}
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
    steps:
      - name: Get CPU info
        run: cat /proc/cpuinfo

      - uses: actions/checkout@v4

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache-on-failure: 'false'

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.7

      - name: Build optimized release
        if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
        run: cargo build --profile=optimized

      - name: Build release
        if: ${{ github.event_name == 'push' }}
        run: cargo build --release

      - name: Size info
        shell: bash
        run: |
          du -hs target/${BUILD_PROFILE_NAME}/pypi-data-toolchain

      - name: Package
        shell: bash
        run: |
          cd target/${BUILD_PROFILE_NAME}
          tar czvf ../../pypi-data-toolchain.tar.gz pypi-data-toolchain
          cd -
      - uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: "latest"
          tag_exists_error: false
          force_push_tag: true
          message: "Latest release"

      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          name: "Latest Release"
          tag_name: "latest"
          files: 'pypi-data-toolchain.tar.gz'
