on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

name: Build
#concurrency: build

jobs:
  build_and_test:
    name: Compile toolchain
    runs-on: ubuntu-latest
    if: github.repository == 'pypi-data/internal-toolchain'
    env:
      RUST_BACKTRACE: "1"
    steps:
      - name: Get CPU info
        run: cat /proc/cpuinfo

      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: ${{ (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && 'optimized' || 'release' }}

      - name: Build optimized release
        uses: actions-rs/cargo@v1
        if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
        with:
          command: build
          args: --profile=optimized

      - name: Build release
        uses: actions-rs/cargo@v1
        if: ${{ github.event_name == 'push' }}
        with:
          command: build
          args: --release

      - name: Size info
        shell: bash
        run: |
          du -hs target/release/pypi-data-toolchain

      - name: Package
        shell: bash
        run: |
          cd target/release
          tar czvf ../../pypi-data-toolchain.tar.gz pypi-data-toolchain
          cd -
      - uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: "latest"
          tag_exists_error: false
          force_push_tag: true
          message: "Latest release"

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          name: "Latest Release"
          tag_name: "latest"
          files: 'pypi-data-toolchain.tar.gz'
