on:
  workflow_dispatch:
  schedule:
    - cron: '0 0-9,11-23 * * *'

name: Trigger

concurrency: trigger

jobs:
  trigger_ci:
    name: Trigger CI
    runs-on: ubuntu-latest
    if: github.repository == 'pypi-data/internal-toolchain'
    steps:
      - uses: robinraju/release-downloader@v1.11
        with:
          repository: "pypi-data/toolchain"
          fileName: "pypi-data-toolchain.tar.gz"
          extract: true
          latest: true
          out-file-path: "toolchain/"

      - name: Generate token
        id: generate_token
        uses: pypi-data/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          ${{ github.workspace }}/toolchain/pypi-data-toolchain list-repositories --sample=250 --progress-less-than=99 > to_run.txt
          
          echo "Triggering the following repositories:"
          echo "Length: $(wc -l to_run.txt)"
          
          while read p; do
            echo "$p"
            ${{ github.workspace }}/toolchain/pypi-data-toolchain trigger-ci "$p" --limit=1500
          done <to_run.txt
