on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

name: Update R2

concurrency: update-r2

jobs:
  update-data:
    name: Trigger CI
    runs-on: ubuntu-latest
    if: github.repository == 'pypi-data/internal-toolchain'
    steps:
      - uses: robinraju/release-downloader@v1.8
        with:
          repository: "pypi-data/toolchain"
          fileName: "pypi-data-toolchain.tar.gz"
          extract: true
          latest: true
          out-file-path: "toolchain/"

      - name: Generate token
        id: generate_token
        uses: pypi-data/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          ${{ github.workspace }}/toolchain/pypi-data-toolchain static-site --content-directory data/ 

      - name: Data size
        run: |
          dh -hs data/

      - name: Set AWS defaults
        run: |
          aws configure set default.s3.max_concurrent_requests 500
          aws configure set default.s3.max_queue_size 10000
          aws configure set default.s3.multipart_threshold 64MB

      - env:
          AWS_ACCESS_KEY_ID: "${{ secrets.R2_ACCESS_KEY }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.R2_SECRET_KEY }}"
        run: |
          aws s3 sync --quiet --size-only data/ s3://pypi-data/data/ --endpoint=${{ secrets.R2_ENDPOINT }} --region=auto --content-encoding=gzip --content-type=application/json