on:
  workflow_dispatch:
    inputs:
      limit:
        description: 'Limit'
        required: true
        type: number
        default: 4
  schedule:
    - cron: '0 2,13 * * *'

name: Update Repositories

concurrency: split-update

jobs:
  update_split:
    name: Update Split
    runs-on: ubuntu-latest
    steps:
      - uses: robinraju/release-downloader@v1.8
        with:
          repository: "pypi-data/pypi-json-data"
          fileName: "pypi-data.sqlite.gz"
          extract: false
          latest: true
          out-file-path: "data/"
      - name: Extract
        shell: bash
        run: gzip -d ${{ github.workspace }}/data/pypi-data.sqlite.gz

      - uses: robinraju/release-downloader@v1.8
        with:
          repository: "pypi-data/toolchain"
          fileName: "pypi-data-toolchain.tar.gz"
          extract: true
          latest: true
          out-file-path: "toolchain/"

      - name: Generate token
        id: generate_token
        uses: pypi-data/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
            
      - name: Create repos
        shell: bash
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          ${{ github.workspace }}/toolchain/pypi-data-toolchain update-repos \
            --sqlite-file=${{ github.workspace }}/data/pypi-data.sqlite \
            --chunk-size=40000 \
            --limit=${{ inputs.limit || 4 }}
